/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package apotekku;

import apotekku.model.Obat;
import apotekku.model.Order;
import apotekku.model.OrderDetail;
import apotekku.model.OrderDetailTableModel;
import apotekku.util.DBcon;
import apotekku.util.DBobatKeluar;
import apotekku.util.PrinterService;
import apotekku.util.Setw;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author user
 */
public class KasirView extends javax.swing.JFrame {

    java.util.Date tglsekarang = new java.util.Date();
    private SimpleDateFormat smpdtfmt = new SimpleDateFormat("dd MMMMMMMMM yyyy", Locale.getDefault());
    //diatas adalah pengaturan format penulisan, bisa diubah sesuai keinginan.
    private String tanggal = smpdtfmt.format(tglsekarang);
    private Connection Con;
    private Statement stm;
    List<OrderDetail> dataOrder = new ArrayList<>();
    DBcon con = new DBcon();
    OrderDetailTableModel tabelmodel;
    Obat obatInput;
    int total = 0;
    int bayar = 0;
    String printerName = "";

    /**
     * Creates new form formmenu
     */
    public KasirView() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        tgl.setText(tanggal);
        setJam();
        setTableOrder();
        obatInput = new Obat();
        obatInput.setID(0);
    }

    private void setTableOrder() {
        tabelmodel = new OrderDetailTableModel(dataOrder);
        tableObat.setModel(tabelmodel);
    }

    public final void setJam() {
        ActionListener taskPerformer = new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent evt) {
                String nol_jam = "", nol_menit = "", nol_detik = "";

                java.util.Date dateTime = new java.util.Date();
                int nilai_jam = dateTime.getHours();
                int nilai_menit = dateTime.getMinutes();
                int nilai_detik = dateTime.getSeconds();

                if (nilai_jam <= 9) {
                    nol_jam = "0";
                }
                if (nilai_menit <= 9) {
                    nol_menit = "0";
                }
                if (nilai_detik <= 9) {
                    nol_detik = "0";
                }

                String jam = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);

                lblwktu.setText(jam + ":" + menit + ":" + detik + "");
            }
        };
        new Timer(1000, taskPerformer).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogBayar = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtTotalBayar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        inputPembayaran = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ketKembalian = new javax.swing.JLabel();
        txtPembayaran = new javax.swing.JTextField();
        txtKembalian = new javax.swing.JTextField();
        dialogPrinter = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        printerList = new javax.swing.JComboBox<>();
        jButton8 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableObat = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        inputKode = new javax.swing.JTextField();
        txtNamaObat = new javax.swing.JTextField();
        txtBigTotal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        inputJumlah = new javax.swing.JTextField();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        tgl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblwktu = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        dialogBayar.setTitle("Pembayaran");
        dialogBayar.setMinimumSize(new java.awt.Dimension(500, 400));
        dialogBayar.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        dialogBayar.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        dialogBayar.setName("Tambah Obat"); // NOI18N
        dialogBayar.setResizable(false);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setText("SIMPAN + CETAK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setText("SIMPAN");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setText("TOTAL :");

        txtTotalBayar.setBackground(new java.awt.Color(255, 255, 102));
        txtTotalBayar.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtTotalBayar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotalBayar.setText("Rp. 0,00");
        txtTotalBayar.setKeymap(null);
        txtTotalBayar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTotalBayarFocusGained(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("PEMBAYARAN :");

        inputPembayaran.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        inputPembayaran.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputPembayaranKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputPembayaranKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Total Bayar :");

        ketKembalian.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ketKembalian.setText("Kekurangan :");

        txtPembayaran.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtPembayaran.setForeground(new java.awt.Color(0, 204, 102));
        txtPembayaran.setKeymap(null);

        txtKembalian.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtKembalian.setKeymap(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(ketKembalian))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTotalBayar, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                            .addComponent(inputPembayaran)
                            .addComponent(txtPembayaran)
                            .addComponent(txtKembalian))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(inputPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ketKembalian)
                    .addComponent(txtKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dialogBayarLayout = new javax.swing.GroupLayout(dialogBayar.getContentPane());
        dialogBayar.getContentPane().setLayout(dialogBayarLayout);
        dialogBayarLayout.setHorizontalGroup(
            dialogBayarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogBayarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        dialogBayarLayout.setVerticalGroup(
            dialogBayarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogBayarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        dialogPrinter.setTitle("Pilih Printer");
        dialogPrinter.setAlwaysOnTop(true);
        dialogPrinter.setMinimumSize(new java.awt.Dimension(400, 150));
        dialogPrinter.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        dialogPrinter.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        dialogPrinter.setName("Pilih Printer"); // NOI18N
        dialogPrinter.setResizable(false);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Pilih Printer : ");

        printerList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton8.setText("PILIH");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(printerList, 0, 119, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(printerList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dialogPrinterLayout = new javax.swing.GroupLayout(dialogPrinter.getContentPane());
        dialogPrinter.getContentPane().setLayout(dialogPrinterLayout);
        dialogPrinterLayout.setHorizontalGroup(
            dialogPrinterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogPrinterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        dialogPrinterLayout.setVerticalGroup(
            dialogPrinterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogPrinterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        dialogPrinter.getAccessibleContext().setAccessibleParent(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistem Informasi Apotek");
        setExtendedState(6);
        setUndecorated(true);
        setResizable(false);

        tableObat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "KODE", "NAMA", "JUMLAH", "HARGA", "TOTAL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableObat.setFillsViewportHeight(true);
        tableObat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tableObatMousePressed(evt);
            }
        });
        tableObat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tableObatKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tableObat);
        tableObat.getAccessibleContext().setAccessibleName("");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("KODE OBAT :");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("NAMA :");

        inputKode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        inputKode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputKodeKeyPressed(evt);
            }
        });

        txtNamaObat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNamaObat.setEnabled(false);
        txtNamaObat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNamaObatKeyTyped(evt);
            }
        });

        txtBigTotal.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        txtBigTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtBigTotal.setText("Rp. 0,00");
        txtBigTotal.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        jLabel3.setText("TOTAL :");

        jButton1.setText("BAYAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setText("RESET");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("JUMLAH :");

        inputJumlah.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        inputJumlah.setText("1");
        inputJumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputJumlahKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputJumlahKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1331, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNamaObat, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addGap(34, 34, 34)
                                    .addComponent(inputKode, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addGap(59, 59, 59)
                                    .addComponent(inputJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(48, 48, 48)
                        .addComponent(txtBigTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(inputKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtNamaObat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(inputJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton4)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBigTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                .addGap(29, 29, 29))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tanggal : ");
        jDesktopPane1.add(jLabel1);
        jLabel1.setBounds(20, 10, 120, 29);

        tgl.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        tgl.setForeground(new java.awt.Color(255, 255, 255));
        tgl.setText("Tanggal");
        jDesktopPane1.add(tgl);
        tgl.setBounds(130, 10, 180, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Jam : ");
        jDesktopPane1.add(jLabel2);
        jLabel2.setBounds(330, 10, 60, 30);

        lblwktu.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblwktu.setForeground(new java.awt.Color(255, 255, 255));
        lblwktu.setText("Jam");
        jDesktopPane1.add(lblwktu);
        lblwktu.setBounds(430, 0, 190, 50);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("TUTUP");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton2);
        jButton2.setBounds(1200, 13, 120, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int a;
        a = JOptionPane.showConfirmDialog(null, "Anda yakin kembali ke Data Penjualan.?", "Informasi", JOptionPane.YES_NO_OPTION);
        if (a == JOptionPane.YES_OPTION) {
            new DataPenjualan().setVisible(true);
            this.dispose();
        } else {
            return;
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bayar(Boolean print) {
        String jmlByar = inputPembayaran.getText();

        if (jmlByar.isEmpty()) {
            JOptionPane.showMessageDialog(dialogBayar, "Jumlah Pembayaran tidak boleh kosong", "Peringatan", JOptionPane.INFORMATION_MESSAGE);
        } else {
            int bayarL = Integer.parseInt(jmlByar);

            if ((bayarL - total) < 0) {
                JOptionPane.showMessageDialog(dialogBayar, "Pembayaran kurang", "Peringatan", JOptionPane.INFORMATION_MESSAGE);
            } else {
                Order order = new Order();
                order.setOrderDetail(dataOrder);
                order.setTotal_harga_jual(tabelmodel.getTotalHarga());
                order.setTotal_bayar(bayarL);
                String invoice = con.insertOrderMasuk(order);
                if (!invoice.isEmpty()) {
                    dialogBayar.setVisible(false);
                    if (print == true) {
                        print(invoice, bayarL);
                    }
                    resetDta();   
                    
                    
                    
                }

            }
        }
    }
    private void tableObatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableObatMousePressed
        // TODO add your handling code here:
//JTable table =(JTable) mouseEvent.getSource();
        Point point = evt.getPoint();
        int row = tableObat.rowAtPoint(point);
        if (evt.getClickCount() == 2 && tableObat.getSelectedRow() != -1) {
            System.out.println("doble clik");
//            showDialogEdit(tableObat.getSelectedRow());
        }
    }//GEN-LAST:event_tableObatMousePressed

    private void tableObatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableObatKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            int index = tableObat.getSelectedRow();
            if (index < 0) {
                JOptionPane.showMessageDialog(null, "Pilih data yang ingin anda hapus", "Peringatan", JOptionPane.INFORMATION_MESSAGE);
            } else {
                tabelmodel.deleteOrder(index);
                setTotal();
            }
        }

    }//GEN-LAST:event_tableObatKeyReleased

    private void txtNamaObatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaObatKeyTyped
        // TODO add your handling code here:
        inputAngka(evt);
    }//GEN-LAST:event_txtNamaObatKeyTyped

    private void inputAngka(java.awt.event.KeyEvent evt) {
        char c = evt.getKeyChar();
        System.out.println("Type : " + c);
        System.out.println("Is digit" + Character.isDigit(c));
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
            evt.consume();
            System.out.println("hapus");
        }
    }

    private void inputKodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputKodeKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            System.out.println("Kosong : " + inputKode.getText().isEmpty());
            if (inputKode.getText().isEmpty()) {
                JOptionPane.showMessageDialog(dialogBayar, "Input Kode tidak boleh kosong", "Peringatan", JOptionPane.INFORMATION_MESSAGE);
            } else {
                obatInput = con.getObatByKodeAda(inputKode.getText());
                if (obatInput.getID() != 0) {
                    txtNamaObat.setText(obatInput.getNama());
                    inputJumlah.requestFocus();
                } else {

                }
            }
        }
    }//GEN-LAST:event_inputKodeKeyPressed

    private void inputJumlahKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputJumlahKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
//            System.out.println("Kosong : " + inputKode.getText().isEmpty());
            if (inputJumlah.getText().isEmpty()) {
                JOptionPane.showMessageDialog(dialogBayar, "Input Jumlah tidak boleh kosong", "Peringatan", JOptionPane.INFORMATION_MESSAGE);
            } else {
                int jumlah = Integer.parseInt(inputJumlah.getText());
                if (obatInput.getID() != 0) {
                    int indexTable = tabelmodel.getOrderByID(obatInput.getID());
                    System.out.println("Index Table : " + indexTable);
                    if (indexTable >= 0) {
                        dataOrder.get(indexTable).setJumlah(jumlah + dataOrder.get(indexTable).getJumlah());
                        dataOrder.get(indexTable).setTotal(dataOrder.get(indexTable).getHarga_jual() * dataOrder.get(indexTable).getJumlah());
                    } else {
                        OrderDetail insertOrder = new OrderDetail();
                        insertOrder.setID_OBAT(obatInput.getID());
                        insertOrder.setKode(obatInput.getKode());
                        insertOrder.setNama(obatInput.getNama());
                        insertOrder.setHarga_jual(obatInput.getHarga());
                        insertOrder.setJumlah(jumlah);
                        insertOrder.setTotal(jumlah * obatInput.getHarga());
                        dataOrder.add(insertOrder);
                    }
                    obatInput.setID(0);
                    setTableOrder();
                    txtNamaObat.setText("");
                    inputKode.setText("");
                    inputJumlah.setText("1");
                    inputKode.requestFocus();
                    setTotal();
                    dialogBayar.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(dialogBayar, "Kode yang dimasukan salah", "Peringatan", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_inputJumlahKeyPressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        resetDta();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void resetDta() {
        dataOrder.clear();
        setTableOrder();
        inputKode.setText("");
        inputJumlah.setText("1");
        inputKode.requestFocus();
        setTotal();
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (total == 0) {
            JOptionPane.showMessageDialog(dialogBayar, "Tidak ada barang yg perlu dibayar", "Peringatan", JOptionPane.INFORMATION_MESSAGE);
        } else {
            dialogBayar.setLocationRelativeTo(jPanel1);
            inputPembayaran.requestFocus();
            txtTotalBayar.setText(setRupiah(total));
            txtKembalian.setText(setRupiah(total));
            txtPembayaran.setText(setRupiah(0));
            ketKembalian.setText("Kekurangan :");
            jButton5.setEnabled(true);
            jButton3.setEnabled(true);
            dialogBayar.setVisible(true);
            jButton1.setEnabled(false);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void inputJumlahKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputJumlahKeyTyped
        // TODO add your handling code here:
        inputAngka(evt);
    }//GEN-LAST:event_inputJumlahKeyTyped

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        bayar(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void inputPembayaranKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputPembayaranKeyTyped
        // TODO add your handling code here:
        inputAngka(evt);
    }//GEN-LAST:event_inputPembayaranKeyTyped

    private void inputPembayaranKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputPembayaranKeyReleased
        // TODO add your handling code here:
        if (!inputPembayaran.getText().isEmpty()) {
            int bayarL = Integer.parseInt(inputPembayaran.getText());
            int kembalian = total - bayarL;
            if (kembalian < 0) {
                ketKembalian.setText("Kembalian :");
                txtKembalian.setText(setRupiah(kembalian * -1));
            } else {
                ketKembalian.setText("Kekurangan :");
                txtKembalian.setText(setRupiah(kembalian));
            }
            txtPembayaran.setText(setRupiah(bayarL));
        }
    }//GEN-LAST:event_inputPembayaranKeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
//        PrinterService printerService = new PrinterService();

//        System.out.println(printerService.getPrinters());
//        if (printerName.isEmpty()) {
//            printerList.removeAllItems();
//            List<String> listPrint = printerService.getPrinters();
//            for (int i = 0; i < listPrint.size(); i++) {
//                printerList.addItem(listPrint.get(i));
//            }
//            dialogPrinter.setLocationRelativeTo(jPanel2);
//            dialogPrinter.setVisible(true);
//        } else {
        bayar(true);
//        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtTotalBayarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTotalBayarFocusGained
        // TODO add your handling code here:
        inputPembayaran.requestFocus();
    }//GEN-LAST:event_txtTotalBayarFocusGained

    private void print(String invoice, int bayar) {
        //print some stuff
//        PrinterService printerService = new PrinterService();
//        String struck
//                = "\n\n "
//                + "INVOICE : " + invoice +"\n"
//                + "===============================\n"
//                + " Qty | Nama         | Total\n"
//                + "===============================\n";
//
//        Setw f = new Setw();
//        for (int i = 0; i < dataOrder.size(); i++) {
//            OrderDetail order = dataOrder.get(i);
//            struck += f.setwL(order.getJumlah() + "", 4) + " | "
//                    + f.setwR(order.getNama(), 12) + " | "
//                    + f.setwL(order.getHarga_jual()+ "", 8) + "\n";
//        }
//        struck += "===============================\n"
//                + "TOTAL : "+f.setwL(tabelmodel.getTotalHarga()+"",22)+"\n"
//                + "BAYAR : "+f.setwL(bayar+"",22)+"\n"
//                + "KEMBALIAN : "+f.setwL(bayar+"",19)+"\n"
//                +"\n\n\n\n";
//        System.out.println(struck);
//        printerService.printString(printerName, struck);

        // cut that paper!
//        byte[] cutP = new byte[]{0x1d, 'V', 1};
//        printerService.printBytes("printerName", cutP);
        try {
//            Class.forName("com.mysql.jdbc.Driver").newInstance();
//            Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost:3306/rumahbersalin", "root", "");
//            HashMap parameter = new HashMap();
            HashMap parameter = new HashMap<String, Object>();
//            DBobatKeluar kwcon = new DBobatKeluar();
            Con = con.getConnection();
            Statement state = Con.createStatement();

            Statement st = Con.createStatement();
            ResultSet rs = st.executeQuery(
                    "SELECT tbl_order.tanggal ,o_detail.id_obat, o_detail.id, o_detail.id_order, o_detail.harga_jual, o_detail.jumlah, o_detail.total,\n"
                    + "       obat.kode, obat.nama\n"
                    + "	FROM tbl_order_detail as o_detail\n"
                    + "	LEFT JOIN tbl_order ON o_detail.id_order = tbl_order.id\n"
                    + "	LEFT JOIN obat ON o_detail.id_obat= obat.id\n"
                    + "	WHERE invoice = \"" + invoice + "\";");
            parameter.put("invoice", ""+invoice);
            parameter.put("bayar", "" + bayar);
            parameter.put("tgl", "" + tanggal);
            parameter.put("total", "" + tabelmodel.getTotalHarga());
            parameter.put("change", "" + (tabelmodel.getTotalHarga() - tabelmodel.getTotalHarga()));
            File file = new File("db/kwitansi.jrxml");

            //            JasperDesign JasperDesign = JRXmlLoader.load(file);
//            net.sf.jasperreports.engine.JasperReport JasperReport = JasperCompileManager.compileReport(JasperDesign);
//            JasperPrint jp = JasperFillManager.fillReport(JasperReport, parameter);
            InputStream reportStream = new FileInputStream(new File("db/kwitansi.jrxml"));
            JasperDesign design = JRXmlLoader.load(reportStream);

            JasperReport report = JasperCompileManager.compileReport(design);
//            JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("db/kwitansi.jasper"), parameter);
            JasperPrint jp = JasperFillManager.fillReport(report, parameter, Con);
            JasperViewer.viewReport(jp, false);
            state.close();
            st.close();
        } catch (JRException e) {

            JOptionPane.showMessageDialog(dialogBayar, "Data tidak dapat dicetak!", "Cetak Data", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(KasirView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(KasirView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        printerName = printerList.getSelectedItem().toString();
        dialogPrinter.setVisible(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void setTotal() {
        total = tabelmodel.getTotalHarga();
        txtBigTotal.setText(setRupiah(total));
    }

    private String setRupiah(int jumlah) {
        DecimalFormat kursIndonesia = (DecimalFormat) DecimalFormat.getCurrencyInstance();
        DecimalFormatSymbols formatRp = new DecimalFormatSymbols();

        formatRp.setCurrencySymbol("Rp. ");
        formatRp.setMonetaryDecimalSeparator(',');
        formatRp.setGroupingSeparator('.');

        kursIndonesia.setDecimalFormatSymbols(formatRp);
        return kursIndonesia.format(jumlah);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KasirView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KasirView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KasirView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KasirView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new KasirView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog dialogBayar;
    private javax.swing.JDialog dialogPrinter;
    private javax.swing.JTextField inputJumlah;
    private javax.swing.JTextField inputKode;
    private javax.swing.JTextField inputPembayaran;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton8;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel ketKembalian;
    private javax.swing.JLabel lblwktu;
    private javax.swing.JComboBox<String> printerList;
    private javax.swing.JTable tableObat;
    private javax.swing.JLabel tgl;
    private javax.swing.JTextField txtBigTotal;
    private javax.swing.JTextField txtKembalian;
    private javax.swing.JTextField txtNamaObat;
    private javax.swing.JTextField txtPembayaran;
    private javax.swing.JTextField txtTotalBayar;
    // End of variables declaration//GEN-END:variables

}
