/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package apotekku;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author user
 */
public class periksa extends javax.swing.JFrame {
java.util.Date tglsekarang = new java.util.Date();
    private SimpleDateFormat smpdtfmt = new SimpleDateFormat("dd/MM/yyyy", Locale.getDefault());
    //diatas adalah pengaturan format penulisan, bisa diubah sesuai keinginan.
    private String tanggal = smpdtfmt.format(tglsekarang);
    
    /**
     * Creates new form tindakan
     */
    public periksa() {
        initComponents();
        setLocationRelativeTo(this);
        setJam();
        tgl.setText(tanggal);
        aktif(false);
        nyala(false);
        //open_db();
    }
public final void setJam(){
ActionListener taskPerformer = new ActionListener() {

            @Override
public void actionPerformed(ActionEvent evt) {
String nol_jam = "", nol_menit = "",nol_detik = "";

java.util.Date dateTime = new java.util.Date();
int nilai_jam = dateTime.getHours();
int nilai_menit = dateTime.getMinutes();
int nilai_detik = dateTime.getSeconds();

if(nilai_jam <= 9) nol_jam= "0";
if(nilai_menit <= 9) nol_menit= "0";
if(nilai_detik <= 9) nol_detik= "0";

String jam = nol_jam + Integer.toString(nilai_jam);
String menit = nol_menit + Integer.toString(nilai_menit);
String detik = nol_detik + Integer.toString(nilai_detik);

lblwktu.setText(jam+":"+menit+":"+detik+"");
}
};
new Timer(1000, taskPerformer).start();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        lblwktu = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tgl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtno = new javax.swing.JTextField();
        txtno_rm = new javax.swing.JTextField();
        txtnm = new javax.swing.JTextField();
        txtpem = new javax.swing.JTextField();
        txtnmtin = new javax.swing.JTextField();
        txthar = new javax.swing.JTextField();
        btcari = new javax.swing.JButton();
        cmbtin = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txthar_ruang = new javax.swing.JTextField();
        cmbruang = new javax.swing.JComboBox();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtada = new javax.swing.JTextField();
        txtjen = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txtnoper = new javax.swing.JTextField();
        cmbnopet = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        txtnamapet = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtdiagnosa = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        cmbobat = new javax.swing.JComboBox();
        txtnmobat = new javax.swing.JTextField();
        txtjumlah = new javax.swing.JTextField();
        txtsat = new javax.swing.JTextField();
        txtharga = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtno_res = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtrin = new javax.swing.JTextField();
        btsim_res = new javax.swing.JButton();
        txtawal = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtakhir = new javax.swing.JTextField();
        txtjenis = new javax.swing.JTextField();
        txtstockmin = new javax.swing.JTextField();
        txtsup = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        btupdateobat = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtjum = new javax.swing.JTextField();
        txttot = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btsimpan = new javax.swing.JButton();
        btbatal = new javax.swing.JButton();
        btkeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Form Tindakan Pemeriksaan");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tindakan Pemeriksaan");
        jDesktopPane1.add(jLabel1);
        jLabel1.setBounds(170, 0, 370, 40);

        lblwktu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblwktu.setText("Jam");

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setText("Jam :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel3.setText("Tanggal :");

        tgl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tgl.setText("Tanggal");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("No Daftar");

        jLabel7.setText("No Rekam Medik");

        jLabel8.setText("Nama Pasien");

        jLabel10.setText("Pemeriksaan");

        jLabel11.setText("Kode Tindakan");

        jLabel5.setText("Nama Tindakan");

        jLabel6.setText("Harga Tindakan");

        txtno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnoActionPerformed(evt);
            }
        });
        txtno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnoKeyReleased(evt);
            }
        });

        btcari.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btcari.setText("Cari");
        btcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcariActionPerformed(evt);
            }
        });

        cmbtin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "::::::: PILIH KODE ::::::::", "T-0001", "T-0002", "T-0003", "T-0004", "T-0005", "T-0006", "T-0007", "T-0008", "T-0009", "T-0010" }));
        cmbtin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbtinActionPerformed(evt);
            }
        });

        jLabel24.setText("Ruang Bersalin");

        jLabel25.setText("Harga Ruang");

        cmbruang.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "= PILIH RUANGAN =", "RUANG MARWAH", "RUANG MUZDALIFAH", "RUANG MULTAZAM", "RUANG SHAFA" }));
        cmbruang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbruangActionPerformed(evt);
            }
        });

        jLabel26.setText("Keadaan Bayi");

        jLabel27.setText("Jenis Kelamin bayi");

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel32.setText("No Periksa");

        txtnoper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnoperActionPerformed(evt);
            }
        });

        cmbnopet.setModel(new javax.swing.DefaultComboBoxModel(new String[] { ":::::::: PILIH KODE ::::::::", "P-0001", "P-0002", "P-0003", "P-0004", "P-0005", "P-0006", "P-0007", "P-0008", "P-0009", "P-0010", " ", " " }));
        cmbnopet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbnopetActionPerformed(evt);
            }
        });

        jLabel13.setText("No Petugas");

        jLabel14.setText("Nama Pemeriksa");

        jLabel21.setText("Diagnosa");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27)
                    .addComponent(jLabel32)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel21))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtdiagnosa, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnamapet, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnoper, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(cmbnopet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtnm)
                            .addComponent(txtpem)
                            .addComponent(txtnmtin)
                            .addComponent(txthar)
                            .addComponent(cmbtin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbruang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txthar_ruang)
                            .addComponent(txtada)
                            .addComponent(txtjen)
                            .addComponent(txtno_rm)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtno, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btcari, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(txtnoper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btcari)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtno_rm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cmbtin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnmtin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txthar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(cmbruang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txthar_ruang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtjen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbnopet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnamapet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtdiagnosa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel15.setText("Kode Obat");

        jLabel16.setText("Nama Obat");

        jLabel18.setText("Jumlah Pemakaian");

        jLabel19.setText("Satuan");

        jLabel20.setText("Harga");

        cmbobat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { ":::::::: PILIH KODE ::::::::", "O-0001", "O-0002", "O-0003", "O-0004", "O-0005", "O-0006", "O-0007", "O-0008", "O-0009", "O-0010" }));
        cmbobat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbobatActionPerformed(evt);
            }
        });

        txtnmobat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnmobatActionPerformed(evt);
            }
        });

        jLabel22.setText("No Resep");

        txtno_res.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtno_resActionPerformed(evt);
            }
        });

        jLabel23.setText("Rincian Obat");

        btsim_res.setText("Simpan Resep");
        btsim_res.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsim_resActionPerformed(evt);
            }
        });

        jLabel28.setText("Stock awal");

        jLabel29.setText("Stock akhir");

        txtakhir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtakhirActionPerformed(evt);
            }
        });

        jLabel12.setText("Jenis");

        jLabel30.setText("Stock min");

        jLabel31.setText("Supplier");

        btupdateobat.setText("Update");
        btupdateobat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btupdateobatActionPerformed(evt);
            }
        });

        jLabel9.setText("Jumlah");

        jLabel17.setText("Total_biaya");

        txtjum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjumActionPerformed(evt);
            }
        });

        txttot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29)
                    .addComponent(jLabel12)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31)
                    .addComponent(jLabel9)
                    .addComponent(jLabel17))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btsim_res)
                        .addComponent(cmbobat, 0, 197, Short.MAX_VALUE)
                        .addComponent(txtnmobat)
                        .addComponent(txtjumlah)
                        .addComponent(txtsat)
                        .addComponent(txtharga)
                        .addComponent(txtno_res)
                        .addComponent(txtrin)
                        .addComponent(txtawal)
                        .addComponent(txtakhir)
                        .addComponent(txtjenis)
                        .addComponent(txtstockmin))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txttot, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtjum, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(txtsup, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btupdateobat))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtno_res, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtrin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btsim_res)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbobat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnmobat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtawal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtakhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtjenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtstockmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(btupdateobat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtjum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txttot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 204, 102));

        btsimpan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btsimpan.setText("Simpan");
        btsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsimpanActionPerformed(evt);
            }
        });

        btbatal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btbatal.setText("Batal");
        btbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbatalActionPerformed(evt);
            }
        });

        btkeluar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btkeluar.setText("Keluar");
        btkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btkeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addComponent(btsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(btbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(btkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btsimpan, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                        .addComponent(btbatal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tgl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblwktu)
                .addGap(115, 115, 115))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblwktu)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(tgl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnmobatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnmobatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnmobatActionPerformed

    private void btkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btkeluarActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btkeluarActionPerformed

    private void cmbtinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbtinActionPerformed
data_tindakan();  
if(cmbtin.getSelectedItem().equals("T-0008")){  
      aktif(true);
}else if(cmbtin.getSelectedItem().equals("T-0007")){nyala(true);}
// TODO add your handling code here:
    }//GEN-LAST:event_cmbtinActionPerformed

    private void btcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcariActionPerformed
        // TODO add your handling code here:
        String no_daftar = txtno.getText();
try
{
Class.forName("com.mysql.jdbc.Driver").newInstance();
Connection koneksi = (Connection) DriverManager.getConnection(
"jdbc:mysql://localhost:3306/rumahbersalin", "root", "");
Statement statement = (Statement) koneksi.createStatement();
String sql="SELECT * FROM daftar WHERE no_daftar like '"+no_daftar+"'";
 ResultSet rs = statement.executeQuery(sql);
if (rs.next())
{
txtno_rm.setText(rs.getString(4));
txtnm.setText(rs.getString(5));
txtpem.setText(rs.getString(6));
JOptionPane.showMessageDialog(null, "Data ditemukan","Informasi",JOptionPane.INFORMATION_MESSAGE);
}
else
{
JOptionPane.showMessageDialog(null, "Data tidak ditemukan ","Informasi",JOptionPane.INFORMATION_MESSAGE);
}
statement.close();
koneksi.close();
}
catch ( ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e)
{
JOptionPane.showMessageDialog(null, "Eror:"+e,"Gagal",JOptionPane.WARNING_MESSAGE);
//System.err.println("Exception: "+e.getMessage());
}     
    }//GEN-LAST:event_btcariActionPerformed

    private void txtnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnoKeyReleased

    private void cmbnopetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbnopetActionPerformed
data_petugas();

// TODO add your handling code here:

    }//GEN-LAST:event_cmbnopetActionPerformed

    private void btbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbatalActionPerformed
        // TODO add your handling code here:
        txtno.setText("");
        txtno_rm.setText("");
        txtnm.setText("");
        txtpem.setText("");
        cmbtin.setSelectedItem(0);
        txtnmtin.setText("");
        txthar.setText("");
        cmbnopet.setSelectedItem(0);
        txtnamapet.setText("");
        cmbobat.setSelectedItem(0);
        txtnmobat.setText("");
        txtjumlah.setText("");
        txtsat.setText("");
        txtharga.setText("");
        txtawal.setText("");
        txtakhir.setText("");
        txtnoper.setText("");
        txtjenis.setText("");
        txtstockmin.setText("");
        txtsup.setText("");
        txtjum.setText("");
        txttot.setText("");
        
        
    }//GEN-LAST:event_btbatalActionPerformed

    private void cmbobatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbobatActionPerformed
        // TODO add your handling code here:
String kode = (String) cmbobat.getSelectedItem();
try
{
Class.forName("com.mysql.jdbc.Driver").newInstance();
Connection koneksi = (Connection) DriverManager.getConnection(
"jdbc:mysql://localhost:3306/rumahbersalin", "root", "");
Statement statement = (Statement) koneksi.createStatement();
String sql="SELECT * FROM obat WHERE kode like '"+kode+"'";
 ResultSet rs = statement.executeQuery(sql);
if (rs.next())
{
txtjumlah.requestFocus();
txtnmobat.setText(rs.getString(2));
txtjenis.setText(rs.getString(3));
txtsat.setText(rs.getString(4));
txtharga.setText(rs.getString(5));
txtawal.setText(rs.getString(6));
txtstockmin.setText(rs.getString(7));
txtsup.setText(rs.getString(8));
} else {
JOptionPane.showMessageDialog(null, "Data Tidak Ada");
} } catch (Exception e){ }
    }//GEN-LAST:event_cmbobatActionPerformed

    private void btsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsimpanActionPerformed
        // TODO add your handling code here:
         String no_per = txtnoper.getText();
         String no_daftar = txtno.getText();
String tanggal = tgl.getText();
String jam = lblwktu.getText();
String no_rm = txtno_rm.getText();
String nama = txtnm.getText();
String kd_tin = (String) cmbtin.getSelectedItem();
String harga = txthar.getText();
String ruang_bersalin = (String) cmbruang.getSelectedItem();
String harga_ruang = txthar_ruang.getText();
String keadaan_bayi = txtada.getText();
String jenkel_bayi = txtjen.getText();
String nip = (String) cmbnopet.getSelectedItem();
String diagnosa = txtdiagnosa.getText();
String no_resep = txtno_res.getText();
String kode = (String) cmbobat.getSelectedItem();
String total_biaya = txttot.getText();
{
try
{
Class.forName("com.mysql.jdbc.Driver").newInstance();
Connection koneksi = (Connection) DriverManager.getConnection(
"jdbc:mysql://localhost:3306/rumahbersalin", "root", "");
Statement statement = (Statement) koneksi.createStatement();
String sql="insert into periksa values('"+no_per+"','"+no_daftar+"','"+tanggal+"','"+jam+"','"+no_rm+"','"+nama+"','"+kd_tin+"','"+ruang_bersalin+"','"+harga_ruang+"','"+keadaan_bayi+"','"+jenkel_bayi+"','"+nip+"','"+diagnosa+"','"+no_resep+"','"+kode+"','"+total_biaya+"')";
int executeUpdate = statement.executeUpdate(sql);
statement.close();
JOptionPane.showMessageDialog(null, "Data berhasil dimasukkan..","Insert Data",JOptionPane.INFORMATION_MESSAGE);
aktif(true);
txtno.setText("");
        txtno_rm.setText("");
        txtnm.setText("");
        txtpem.setText("");
        cmbtin.setSelectedItem(0);
        txtnmtin.setText("");
        txthar.setText("");
        cmbnopet.setSelectedItem(0);
        txtnamapet.setText("");
        cmbobat.setSelectedItem(0);
        txtnmobat.setText("");
        txtjumlah.setText("");
        txtsat.setText("");
        txtharga.setText("");
        txtawal.setText("");
        txtakhir.setText("");
        txtnoper.setText("");
        txtjenis.setText("");
        txtstockmin.setText("");
        txtsup.setText("");
        txtjum.setText("");
        txttot.setText("");
        new formtrans().setVisible(true);
        this.dispose();
koneksi.close();
}
catch (     ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e)
{
JOptionPane.showMessageDialog(null, "Eror: "+e,"Gagal",JOptionPane.WARNING_MESSAGE);
//System.err.println("Exception: "+e.getMessage());
}
    }
    }//GEN-LAST:event_btsimpanActionPerformed

    private void txtnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnoActionPerformed

    private void txtno_resActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtno_resActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection koneksi = (Connection) DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/rumahbersalin", "root", "");
            Statement statement = (Statement) koneksi.createStatement();
            String sql = "SELECT * FROM resep order by no_resep";
            ResultSet rs = statement.executeQuery(sql);
            if (rs.first() == false) {
                txtno_res.setText("000001");
            } else {
                rs.last();
                int no = rs.getInt(1) + 1;
                String cno=String.valueOf(no);
                int pjg_cno=cno.length();
                for (int i=0;i<3-pjg_cno;i++)
                {
                cno="0"+cno;
                }
                txtno_res.setText("000"+cno);

            }
            statement.close();
            koneksi.close();
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Eror:" + e, "Gagal", JOptionPane.WARNING_MESSAGE);
//System.err.println("Exception: "+e.getMessage());
        }
    }//GEN-LAST:event_txtno_resActionPerformed

    private void cmbruangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbruangActionPerformed
        // TODO add your handling code here:
        if(cmbruang.getSelectedItem().equals("RUANG MARWAH")){  
      txthar_ruang.setText("100000");  
  }  
  else if(cmbruang.getSelectedItem().equals("RUANG MUZDALIFAH")){  
      txthar_ruang.setText("90000");  
  }
  else if(cmbruang.getSelectedItem().equals("RUANG MULTAZAM")){  
      txthar_ruang.setText("30000");  
  }
       else{txthar_ruang.setText("75000");  
  }

    }//GEN-LAST:event_cmbruangActionPerformed

    private void btsim_resActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsim_resActionPerformed
        // TODO add your handling code here:
        String no_resep = txtno_res.getText();
String tgl_resep = tgl.getText();
String rincian_obat = txtrin.getText();
{
try
{
Class.forName("com.mysql.jdbc.Driver").newInstance();
Connection koneksi = (Connection) DriverManager.getConnection(
"jdbc:mysql://localhost:3306/rumahbersalin", "root", "");
Statement statement = (Statement) koneksi.createStatement();
String sql="insert into resep values('"+no_resep+"','"+tgl_resep+"','"+rincian_obat+"')";
int executeUpdate = statement.executeUpdate(sql);
statement.close();
JOptionPane.showMessageDialog(null, "Data berhasil disimpan.!","Insert Data",JOptionPane.INFORMATION_MESSAGE);
aktif(true);
        txtrin.setText("");
koneksi.close();
}
catch (     ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e)
{
JOptionPane.showMessageDialog(null, "Eror: "+e,"Gagal",JOptionPane.WARNING_MESSAGE);
//System.err.println("Exception: "+e.getMessage());
}
    }
    }//GEN-LAST:event_btsim_resActionPerformed

    private void txtakhirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtakhirActionPerformed
        // TODO add your handling code here:
        double xakh,xawl,xjml;
    xawl=Double.parseDouble(txtawal.getText());
    xjml=Double.parseDouble(txtjumlah.getText());
    xakh=xawl-xjml;
    String xtotal=Double.toString(xakh);
    txtakhir.setText(xtotal);
    }//GEN-LAST:event_txtakhirActionPerformed

    private void btupdateobatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btupdateobatActionPerformed
        // TODO add your handling code here:
        obat();
    }//GEN-LAST:event_btupdateobatActionPerformed

    private void txtjumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjumActionPerformed
        // TODO add your handling code here:
        double xtot,xhrg,xjml;
    xhrg=Double.parseDouble(txtharga.getText());
    xjml=Double.parseDouble(txtjumlah.getText());
    xtot=xjml*xhrg;
    String xtotal=Double.toString(xtot);
    txtjum.setText(xtotal);
    }//GEN-LAST:event_txtjumActionPerformed

    private void txttotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotActionPerformed
hitung();        // TODO add your handling code here:
    }//GEN-LAST:event_txttotActionPerformed

    private void txtnoperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnoperActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection koneksi = (Connection) DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/rumahbersalin", "root", "");
            Statement statement = (Statement) koneksi.createStatement();
            String sql = "SELECT * FROM periksa order by no_per";
            ResultSet rs = statement.executeQuery(sql);
            if (rs.first() == false) {
                txtnoper.setText("000001");
            } else {
                rs.last();
                int no = rs.getInt(1) + 1;
                String cno=String.valueOf(no);
                int pjg_cno=cno.length();
                for (int i=0;i<3-pjg_cno;i++)
                {
                cno="0"+cno;
                }
                txtnoper.setText("000"+cno);

            }
            statement.close();
            koneksi.close();
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Eror:" + e, "Gagal", JOptionPane.WARNING_MESSAGE);
//System.err.println("Exception: "+e.getMessage());
        }
    }//GEN-LAST:event_txtnoperActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(periksa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new periksa().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbatal;
    private javax.swing.JButton btcari;
    private javax.swing.JButton btkeluar;
    private javax.swing.JButton btsim_res;
    private javax.swing.JButton btsimpan;
    private javax.swing.JButton btupdateobat;
    private javax.swing.JComboBox cmbnopet;
    private javax.swing.JComboBox cmbobat;
    private javax.swing.JComboBox cmbruang;
    private javax.swing.JComboBox cmbtin;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblwktu;
    private javax.swing.JLabel tgl;
    private javax.swing.JTextField txtada;
    private javax.swing.JTextField txtakhir;
    private javax.swing.JTextField txtawal;
    private javax.swing.JTextField txtdiagnosa;
    private javax.swing.JTextField txthar;
    private javax.swing.JTextField txthar_ruang;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtjen;
    private javax.swing.JTextField txtjenis;
    private javax.swing.JTextField txtjum;
    private javax.swing.JTextField txtjumlah;
    private javax.swing.JTextField txtnamapet;
    private javax.swing.JTextField txtnm;
    private javax.swing.JTextField txtnmobat;
    private javax.swing.JTextField txtnmtin;
    private javax.swing.JTextField txtno;
    private javax.swing.JTextField txtno_res;
    private javax.swing.JTextField txtno_rm;
    private javax.swing.JTextField txtnoper;
    private javax.swing.JTextField txtpem;
    private javax.swing.JTextField txtrin;
    private javax.swing.JTextField txtsat;
    private javax.swing.JTextField txtstockmin;
    private javax.swing.JTextField txtsup;
    private javax.swing.JTextField txttot;
    // End of variables declaration//GEN-END:variables

    


    private void data_tindakan() {
 String kd_tin = (String) cmbtin.getSelectedItem();
try
{
Class.forName("com.mysql.jdbc.Driver").newInstance();
Connection koneksi = (Connection) DriverManager.getConnection(
"jdbc:mysql://localhost:3306/rumahbersalin", "root", "");
Statement statement = (Statement) koneksi.createStatement();
String sql="SELECT * FROM tindakan where kd_tin like '"+kd_tin+"'";
 ResultSet rs = statement.executeQuery(sql);
if (rs.next())
{
txtnmtin.setText(rs.getString(2));
txthar.setText(rs.getString(3));
} 
else {
JOptionPane.showMessageDialog(null, "Data Tidak Ada");
} } catch (Exception e){ }

}

    private void aktif(boolean x) {
      txtno_rm.setEditable(x);
      txtnm.setEditable(x);
      txtnmtin.setEditable(x);
      txtharga.setEditable(x);
      txthar.setEditable(x);
      txtnamapet.setEditable(x);
      txtnmobat.setEditable(x);
      txtpem.setEditable(x);
      txtsat.setEditable(x);
      txthar_ruang.setEditable(x);
      cmbruang.setEnabled(x);
      txtada.setEditable(x);
      txtjen.setEditable(x);
      txtstockmin.setEditable(x);
      txtsup.setEditable(x);
      txtjenis.setEditable(x);
      txtawal.setEditable(x);
      
    }

    private void data_petugas() {
        String nip = (String) cmbnopet.getSelectedItem();
try
{
Class.forName("com.mysql.jdbc.Driver").newInstance();
Connection koneksi = (Connection) DriverManager.getConnection(
"jdbc:mysql://localhost:3306/rumahbersalin", "root", "");
Statement statement = (Statement) koneksi.createStatement();
String sql="SELECT * FROM bidan WHERE nip like '"+nip+"'";
 ResultSet rs = statement.executeQuery(sql);
if (rs.next())
{
txtnamapet.setText(rs.getString(2));
} else {
JOptionPane.showMessageDialog(null, "Data Tidak Ada");
} } catch (Exception e){ }
    }

    private void nyala(boolean a) {
        txtdiagnosa.setEditable(a);
      txtno_res.setEditable(a);
      txtrin.setEditable(a);
      btsim_res.setEnabled(a);
    }

    private void obat() {
String kode = (String) cmbobat.getSelectedItem();
String nama_obat = txtnmobat.getText();
String jenis = txtjenis.getText();
String satuan = txtsat.getText();
String harga = txtharga.getText();
String stok = txtakhir.getText();
String stokmin = txtstockmin.getText();
String suplier = txtsup.getText();
try {
Class.forName("com.mysql.jdbc.Driver").newInstance();
Connection koneksi = (Connection) DriverManager.getConnection(
"jdbc:mysql://localhost:3306/rumahbersalin", "root", "");
Statement statement = (Statement) koneksi.createStatement();
String sql="UPDATE obat SET NAMA_OBAT='"+nama_obat+"',JENIS='"+jenis+"',SATUAN='"+satuan+"',HARGA='"+harga+"',STOK='"+stok+"',STOKMIN='"+stokmin+"',SUPLIER='"+suplier+"' WHERE kode LIKE '"+kode+"'";
statement.executeUpdate(sql);
statement.close();
JOptionPane.showMessageDialog(null, "Data berhasil diedit..","Insert Data",JOptionPane.INFORMATION_MESSAGE);
koneksi.close();
} catch (ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e) {
JOptionPane.showMessageDialog(null, "Eror: "+e,"Gagal",JOptionPane.WARNING_MESSAGE);
//System.err.println("Exception: "+e.getMessage());
}
    }

    private void hitung() {
        if(txthar_ruang.getText().equals("")){  
                double xtot,xhrg,xjml;
    xhrg=Double.parseDouble(txthar.getText());
    xjml=Double.parseDouble(txtjum.getText());
    xtot=xjml+xhrg;
    String xtotal=Double.toString(xtot);
    txttot.setText(xtotal);
      
}else {
         double xtot,xhrg,xjml,xrng;
    xhrg=Double.parseDouble(txthar.getText());
    xjml=Double.parseDouble(txtjum.getText());
    xrng=Double.parseDouble(txthar_ruang.getText());
    xtot=xjml+xhrg+xrng;
    String xtotal=Double.toString(xtot);
    txttot.setText(xtotal);
    }
    }

    
}
